set-window-option -g base-index 1
set-window-option -g pane-base-index 1
set-option -g mode-keys vi
set-option -g prefix C-Space
set-option -g allow-rename off
set-option -g automatic-rename off
set-option -g mouse on
set-option -g mouse-utf8 on
set -s escape-time 0
# set-option -g default-terminal "screen-256color"
set -g default-terminal "xterm-256color"

set -g default-shell $SHELL 
set -g default-command "reattach-to-user-namespace -l ${SHELL}"

bind-key F1 select-layout '6a70,425x93,0,0{113x93,0,0[113x23,0,0,0,113x24,0,24,3,113x44,0,49,4],311x93,114,0,5}'
bind-key F2 select-layout 'b769,278x65,0,0{83x65,0,0[83x16,0,0,0,83x16,0,17,3,83x31,0,34,4],194x65,84,0,5}'
bind-key F3 select-layout 'fdce,278x65,0,0{102x65,0,0[102x17,0,0,0,102x15,0,18,3,102x31,0,34,15],175x65,103,0,5}'

# unbind-key -T prefix Space
# bind-key -T prefix Space select-pane -t :.+
# bind-key -T prefix C-Space select-pane -t :.+
# 
# unbind-key -T prefix o
# bind-key -T prefix o last-pane

unbind-key -T prefix Space
unbind-key -T prefix C-Space
bind-key -T prefix Space last-pane
bind-key -T prefix C-Space last-pane

unbind-key -T prefix \;
bind-key -T prefix \; last-window

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-copycat'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# run-shell "powerline-daemon -q"
# source "/usr/local/lib/python3.5/site-packages/powerline/bindings/tmux/powerline.conf"
