source $HOME/.config/nvim/plugins.vim
source $HOME/.config/nvim/options.vim
source $HOME/.config/nvim/mappings.vim
source $HOME/.config/nvim/styling.vim
source $HOME/.config/nvim/tabwidth.vim
source $HOME/.config/nvim/youcompleteme.vim
source $HOME/.config/nvim/neomake.vim
source $HOME/.config/nvim/fzf.vim
source $HOME/.config/nvim/nerdtree.vim
source $HOME/.config/nvim/plugin_options.vim
source $HOME/.config/nvim/coc.vim
